//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Element", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Element : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WinFormClient.ServiceReference1.HelloWorldResponse HelloWorld(WinFormClient.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WinFormClient.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WinFormClient.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        int Add(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fromCtoF", ReplyAction="*")]
        double fromCtoF(double C);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fromCtoF", ReplyAction="*")]
        System.Threading.Tasks.Task<double> fromCtoFAsync(double C);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fromFtoC", ReplyAction="*")]
        double fromFtoC(double F);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fromFtoC", ReplyAction="*")]
        System.Threading.Tasks.Task<double> fromFtoCAsync(double F);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCurrentDateAndTime", ReplyAction="*")]
        System.DateTime getCurrentDateAndTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCurrentDateAndTime", ReplyAction="*")]
        System.Threading.Tasks.Task<System.DateTime> getCurrentDateAndTimeAsync();
        
        // CODEGEN: Generating message contract since element name getListOfElementsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getListOfElements", ReplyAction="*")]
        WinFormClient.ServiceReference1.getListOfElementsResponse getListOfElements(WinFormClient.ServiceReference1.getListOfElementsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getListOfElements", ReplyAction="*")]
        System.Threading.Tasks.Task<WinFormClient.ServiceReference1.getListOfElementsResponse> getListOfElementsAsync(WinFormClient.ServiceReference1.getListOfElementsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/leiToEuro", ReplyAction="*")]
        double leiToEuro(double lei);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/leiToEuro", ReplyAction="*")]
        System.Threading.Tasks.Task<double> leiToEuroAsync(double lei);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/euroToLei", ReplyAction="*")]
        double euroToLei(double euro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/euroToLei", ReplyAction="*")]
        System.Threading.Tasks.Task<double> euroToLeiAsync(double euro);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WinFormClient.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WinFormClient.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WinFormClient.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WinFormClient.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListOfElementsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getListOfElements", Namespace="http://tempuri.org/", Order=0)]
        public WinFormClient.ServiceReference1.getListOfElementsRequestBody Body;
        
        public getListOfElementsRequest() {
        }
        
        public getListOfElementsRequest(WinFormClient.ServiceReference1.getListOfElementsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getListOfElementsRequestBody {
        
        public getListOfElementsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListOfElementsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getListOfElementsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WinFormClient.ServiceReference1.getListOfElementsResponseBody Body;
        
        public getListOfElementsResponse() {
        }
        
        public getListOfElementsResponse(WinFormClient.ServiceReference1.getListOfElementsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getListOfElementsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WinFormClient.ServiceReference1.Element[] getListOfElementsResult;
        
        public getListOfElementsResponseBody() {
        }
        
        public getListOfElementsResponseBody(WinFormClient.ServiceReference1.Element[] getListOfElementsResult) {
            this.getListOfElementsResult = getListOfElementsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WinFormClient.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WinFormClient.ServiceReference1.WebService1Soap>, WinFormClient.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinFormClient.ServiceReference1.HelloWorldResponse WinFormClient.ServiceReference1.WebService1Soap.HelloWorld(WinFormClient.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WinFormClient.ServiceReference1.HelloWorldRequest inValue = new WinFormClient.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WinFormClient.ServiceReference1.HelloWorldRequestBody();
            WinFormClient.ServiceReference1.HelloWorldResponse retVal = ((WinFormClient.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WinFormClient.ServiceReference1.HelloWorldResponse> WinFormClient.ServiceReference1.WebService1Soap.HelloWorldAsync(WinFormClient.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WinFormClient.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WinFormClient.ServiceReference1.HelloWorldRequest inValue = new WinFormClient.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WinFormClient.ServiceReference1.HelloWorldRequestBody();
            return ((WinFormClient.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Add(int a, int b) {
            return base.Channel.Add(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int a, int b) {
            return base.Channel.AddAsync(a, b);
        }
        
        public double fromCtoF(double C) {
            return base.Channel.fromCtoF(C);
        }
        
        public System.Threading.Tasks.Task<double> fromCtoFAsync(double C) {
            return base.Channel.fromCtoFAsync(C);
        }
        
        public double fromFtoC(double F) {
            return base.Channel.fromFtoC(F);
        }
        
        public System.Threading.Tasks.Task<double> fromFtoCAsync(double F) {
            return base.Channel.fromFtoCAsync(F);
        }
        
        public System.DateTime getCurrentDateAndTime() {
            return base.Channel.getCurrentDateAndTime();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> getCurrentDateAndTimeAsync() {
            return base.Channel.getCurrentDateAndTimeAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinFormClient.ServiceReference1.getListOfElementsResponse WinFormClient.ServiceReference1.WebService1Soap.getListOfElements(WinFormClient.ServiceReference1.getListOfElementsRequest request) {
            return base.Channel.getListOfElements(request);
        }
        
        public WinFormClient.ServiceReference1.Element[] getListOfElements() {
            WinFormClient.ServiceReference1.getListOfElementsRequest inValue = new WinFormClient.ServiceReference1.getListOfElementsRequest();
            inValue.Body = new WinFormClient.ServiceReference1.getListOfElementsRequestBody();
            WinFormClient.ServiceReference1.getListOfElementsResponse retVal = ((WinFormClient.ServiceReference1.WebService1Soap)(this)).getListOfElements(inValue);
            return retVal.Body.getListOfElementsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WinFormClient.ServiceReference1.getListOfElementsResponse> WinFormClient.ServiceReference1.WebService1Soap.getListOfElementsAsync(WinFormClient.ServiceReference1.getListOfElementsRequest request) {
            return base.Channel.getListOfElementsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WinFormClient.ServiceReference1.getListOfElementsResponse> getListOfElementsAsync() {
            WinFormClient.ServiceReference1.getListOfElementsRequest inValue = new WinFormClient.ServiceReference1.getListOfElementsRequest();
            inValue.Body = new WinFormClient.ServiceReference1.getListOfElementsRequestBody();
            return ((WinFormClient.ServiceReference1.WebService1Soap)(this)).getListOfElementsAsync(inValue);
        }
        
        public double leiToEuro(double lei) {
            return base.Channel.leiToEuro(lei);
        }
        
        public System.Threading.Tasks.Task<double> leiToEuroAsync(double lei) {
            return base.Channel.leiToEuroAsync(lei);
        }
        
        public double euroToLei(double euro) {
            return base.Channel.euroToLei(euro);
        }
        
        public System.Threading.Tasks.Task<double> euroToLeiAsync(double euro) {
            return base.Channel.euroToLeiAsync(euro);
        }
    }
}
